apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.8.0
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_PROCESS_ROLES
          value: "broker"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-kraft:29093"
        - name: KAFKA_STORAGE_DIR
          value: "/var/lib/kafka/data"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_KRAFT_MODE
          value: "true"
        - name: CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: kafka-cluster-id-secret
              key: cluster-id
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - name: external-9092
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: internal-29092
    port: 29092
    targetPort: 29092
    protocol: TCP
  selector:
    app: kafka
