apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-streaming-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-streaming
  template:
    metadata:
      labels:
        app: event-streaming
    spec:
      containers:
      - name: event-streaming-container
        image: confluentinc/cp-kafka:7.8.0
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@event-streaming-kraft:29093"  # Match the service name here
        - name: KAFKA_STORAGE_DIR
          value: "/var/lib/event-streaming/data"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/event-streaming/data"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_KRAFT_MODE
          value: "true"
        - name: CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: kafka-cluster-id-secret
              key: cluster-id
        volumeMounts:
        - name: event-streaming-data
          mountPath: /var/lib/event-streaming/data
      volumes:
      - name: event-streaming-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: event-streaming-kraft  # Updated to match the hostname in KAFKA_CONTROLLER_QUORUM_VOTERS
spec:
  type: LoadBalancer
  ports:
  - name: external-9092
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: internal-29092
    port: 29092
    targetPort: 29092
    protocol: TCP
  - name: internal-controller-29093  # Added port for controller communication
    port: 29093
    targetPort: 29093
    protocol: TCP
  selector:
    app: event-streaming
